### ISSUE TITLE
calibration lesson refers to Rscript, but it can't find it

### ISSUE THREAD

**Issue by mollymca** [NCAR/wrf_hydro_training#108]
How can we help you?
The Docker container is great!  One quick question though - the calibration
lesson refers to Rscript, but it can't find it.  See below for additional
details.  Any suggestions?

Thanks,

Kellie
vachek@engr.orst.edu

CalledProcessError                        Traceback (most recent call last)
  in
----> 1 get_ipython().run_cell_magic('bash', '', 'Rscript
/home/docker/wrf-hydro-training/example_case/convert_usgs_to_Rdata.R\n')

~/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py in
run_cell_magic(self, magic_name, line, cell)
    2319             magic_arg_s = self.var_expand(line, stack_depth)
    2320             with self.builtin_trap:
-> 2321                 result = fn(magic_arg_s, cell)
    2322             return result
    2323

~/miniconda3/lib/python3.7/site-packages/IPython/core/magics/script.py in
named_script_magic(line, cell)
     140             else:
     141                 line = script
--> 142             return self.shebang(line, cell)
     143
     144         # write a basic docstring:

  in shebang(self, line, cell)

~/miniconda3/lib/python3.7/site-packages/IPython/core/magic.py in (f, *a,
**k)
     185     # but it's overkill for just that one bit of state.
     186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
     188
     189         if callable(arg):

~/miniconda3/lib/python3.7/site-packages/IPython/core/magics/script.py in
shebang(self, line, cell)
     243             sys.stderr.flush()
     244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out,
stderr=err)
     246
     247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'Rscript
/home/docker/wrf-hydro-training/example_case/convert_usgs_to_Rdata.R\n''
returned non-zero exit status 127.

**Comment by kafitzgerald** [comment]
This is very likely related to issue #109.  I am guessing Kellie was trying to run the calibration lesson from within the wrfhydro/training Docker container and unsurprisingly (to us) that won't work.  Moving the calibration lesson out of the training container should alleviate some confusion.

**Comment by kafitzgerald** [comment]
Pull request #110 moves the calibration lesson into a separate 'internal' folder so that folks won't try to run this from within the standard training container.
