### ISSUE TITLE
jupyter, Lesson-2-run.ipynb bug?

### ISSUE THREAD

**Issue by ashalper-usgs** [NCAR/wrf_hydro_training#93]
Is this a known bug in `Lesson-2-run.ipynb`?

![image](https://user-images.githubusercontent.com/6117231/41426569-dd33c530-6fb8-11e8-861d-ab8e91844c1e.png)

Thanks,
Andy Halper

**Comment by jmills-ncar** [comment]
I have not seen this bug before, are you running in the training docker container or on a local jupyter instance?

**Comment by ashalper-usgs** [comment]
The training Docker container. The only slightly odd thing I can think of is that I think I may have pressed the jupyter `Run` button more times than necessary in the previous, `Lesson-1-compile.ipynb`, but don't know if that might be related.

**Comment by ashalper-usgs** [comment]
Very good. Thanks!

**Comment by jmills-ncar** [comment]
ok the recent PR should fix the issue and I have tagged a release. You should be good to go but if not followup.

Thanks

**Comment by ashalper-usgs** [comment]
Excellent. Seems to have fixed it. Thanks again.
